const randomData = [
  {
    fullName: 'Vladimir Etty',
    email: 'vetty0@freewebs.com',
    phone: '6146625527',
    department: 'Accounting',
    dateOfBirth: '2021-10-12 19:29:17',
    projectName: 'Tampflex',
    projectSubmit: 'yes',
    vaccinationFirstDose: 0,
    vaccinationSecondDose: 1,
  },
  {
    fullName: 'Lucilia Vinton',
    email: 'lvinton1@privacy.gov.au',
    phone: '3325689120',
    department: 'Research and Development',
    dateOfBirth: '2022-03-29 04:52:07',
    projectName: 'Cardify',
    projectSubmit: 'yes',
    vaccinationFirstDose: 1,
    vaccinationSecondDose: 0,
  },
  {
    fullName: 'Thornton Harbage',
    email: 'tharbage2@dailymotion.com',
    phone: '3622431222',
    department: 'Research and Development',
    dateOfBirth: '2021-03-21 23:38:18',
    projectName: 'Alphazap',
    projectSubmit: 'yes',
    vaccinationFirstDose: 0,
    vaccinationSecondDose: 1,
  },
  {
    fullName: 'Myca Santoro',
    email: 'msantoro3@smh.com.au',
    phone: '1753674454',
    department: 'Sales',
    dateOfBirth: '2020-11-05 19:32:16',
    projectName: 'Sonair',
    projectSubmit: 'yes',
    vaccinationFirstDose: 1,
    vaccinationSecondDose: 1,
  },
  {
    fullName: 'Tonya Montrose',
    email: 'tmontrose4@tmall.com',
    phone: '6537919546',
    department: 'Accounting',
    dateOfBirth: '2021-08-12 05:23:42',
    projectName: 'Solarbreeze',
    projectSubmit: 'yes',
    vaccinationFirstDose: 0,
    vaccinationSecondDose: 1,
  },
  {
    fullName: 'Heloise Clell',
    email: 'hclell5@europa.eu',
    phone: '3716036618',
    department: 'Sales',
    dateOfBirth: '2021-10-31 01:36:26',
    projectName: 'Quo Lux',
    projectSubmit: 'yes',
    vaccinationFirstDose: 0,
    vaccinationSecondDose: 1,
  },
  {
    fullName: 'Holli Arends',
    email: 'harends6@newyorker.com',
    phone: '2111726283',
    department: 'Support',
    dateOfBirth: '2021-06-26 19:50:32',
    projectName: 'Cardguard',
    projectSubmit: 'yes',
    vaccinationFirstDose: 0,
    vaccinationSecondDose: 1,
  },
  {
    fullName: 'Norby Penny',
    email: 'npenny7@arstechnica.com',
    phone: '8154865217',
    department: 'Marketing',
    dateOfBirth: '2021-12-06 09:18:51',
    projectName: 'Tampflex',
    projectSubmit: 'yes',
    vaccinationFirstDose: 1,
    vaccinationSecondDose: 0,
  },
  {
    fullName: 'Gisella Reicherz',
    email: 'greicherz8@fda.gov',
    phone: '3016429035',
    department: 'Services',
    dateOfBirth: '2022-01-21 11:34:32',
    projectName: 'Alphazap',
    projectSubmit: 'yes',
    vaccinationFirstDose: 1,
    vaccinationSecondDose: 0,
  },
  {
    fullName: 'Brynna Haggith',
    email: 'bhaggith9@cargocollective.com',
    phone: '1918400750',
    department: 'Training',
    dateOfBirth: '2021-10-02 14:52:10',
    projectName: 'Sonsing',
    projectSubmit: 'yes',
    vaccinationFirstDose: 1,
    vaccinationSecondDose: 1,
  },
  {
    fullName: 'Eydie Wippermann',
    email: 'ewippermanna@usa.gov',
    phone: '6453959422',
    department: 'Human Resources',
    dateOfBirth: '2022-04-10 03:48:29',
    projectName: 'Alphazap',
    projectSubmit: 'yes',
    vaccinationFirstDose: 0,
    vaccinationSecondDose: 1,
  },
  {
    fullName: 'Orsola Blackstock',
    email: 'oblackstockb@nhs.uk',
    phone: '4142658748',
    department: 'Accounting',
    dateOfBirth: '2021-10-28 23:31:12',
    projectName: 'Job',
    projectSubmit: 'yes',
    vaccinationFirstDose: 1,
    vaccinationSecondDose: 0,
  },
  {
    fullName: 'Pet Babar',
    email: 'pbabarc@google.co.uk',
    phone: '4664371777',
    department: 'Legal',
    dateOfBirth: '2021-09-06 12:04:22',
    projectName: 'Cardguard',
    projectSubmit: 'yes',
    vaccinationFirstDose: 0,
    vaccinationSecondDose: 0,
  },
  {
    fullName: 'Ag Troy',
    email: 'atroyd@freewebs.com',
    phone: '3992262519',
    department: 'Sales',
    dateOfBirth: '2022-03-14 23:16:39',
    projectName: 'Tresom',
    projectSubmit: 'yes',
    vaccinationFirstDose: 1,
    vaccinationSecondDose: 0,
  },
  {
    fullName: 'Gaspar Starford',
    email: 'gstarforde@elegantthemes.com',
    phone: '4167413202',
    department: 'Sales',
    dateOfBirth: '2021-09-16 23:22:47',
    projectName: 'Hatity',
    projectSubmit: 'yes',
    vaccinationFirstDose: 1,
    vaccinationSecondDose: 1,
  },
  {
    fullName: 'Cornelia Riehm',
    email: 'criehmf@time.com',
    phone: '8271408151',
    department: 'Business Development',
    dateOfBirth: '2022-05-02 18:26:55',
    projectName: 'Domainer',
    projectSubmit: 'yes',
    vaccinationFirstDose: 1,
    vaccinationSecondDose: 0,
  },
  {
    fullName: 'Brigida Ledgerton',
    email: 'bledgertong@taobao.com',
    phone: '6589512473',
    department: 'Human Resources',
    dateOfBirth: '2021-07-31 04:11:14',
    projectName: 'Cardify',
    projectSubmit: 'yes',
    vaccinationFirstDose: 0,
    vaccinationSecondDose: 1,
  },
  {
    fullName: 'Gilbertina Blasetti',
    email: 'gblasettih@dropbox.com',
    phone: '7746904370',
    department: 'Marketing',
    dateOfBirth: '2020-11-03 05:32:44',
    projectName: 'Stringtough',
    projectSubmit: 'yes',
    vaccinationFirstDose: 1,
    vaccinationSecondDose: 1,
  },
  {
    fullName: 'Nelie Dowley',
    email: 'ndowleyi@columbia.edu',
    phone: '8935388079',
    department: 'Sales',
    dateOfBirth: '2021-11-29 00:57:25',
    projectName: 'Cookley',
    projectSubmit: 'yes',
    vaccinationFirstDose: 0,
    vaccinationSecondDose: 1,
  },
  {
    fullName: 'Estel Wheatland',
    email: 'ewheatlandj@a8.net',
    phone: '6324918238',
    department: 'Accounting',
    dateOfBirth: '2021-03-08 17:40:16',
    projectName: 'Y-Solowarm',
    projectSubmit: 'yes',
    vaccinationFirstDose: 1,
    vaccinationSecondDose: 1,
  },
];

exports.randomData = randomData;
